# Generated by Django 4.1 on 2022-09-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_mywatchlist_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlist',
            name='review',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='mywatchlist',
            name='watched',
            field=models.TextField(default=''),
        ),
    ]
